---
services:
  twitcasting-rec:
    image: ghcr.io/miutaku/rec-twitcasting:latest
    container_name: twitcasting-rec
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
      - ./recorded:./recorded
#      - /your/path/to/dir:./recorded
    environment:
      - TZ=Asia/Tokyo
      - TWITCASTING_CLIENT_ID=YOUR_TWITCASTING_CLIENT_ID
      - TWITCASTING_CLIENT_SECRET=YOUR_TWITCASTING_CLIENT_SECRET
