---
services:
# rec-api
  api-rec-twitcasting:
    image: ghcr.io/miutaku/api-rec-twitcasting:latest
    container_name: api-rec-twitcasting
    restart: unless-stopped
    volumes:
      - ./recorded:./recorded
#      - /your/path/to/dir:./recorded
    environment:
      - TZ=Asia/Tokyo
      - TWITCASTING_CLIENT_ID=YOUR_TWITCASTING_CLIENT_ID
      - TWITCASTING_CLIENT_SECRET=YOUR_TWITCASTING_CLIENT_SECRET

# batch
  batch-rec-twitcasting:
    build:
      context: ./batch
      dockerfile: Dockerfile
    container_name: batch-rec-twitcasting
    environment:
      - FETCH_INTERVAL_SEC=1
      #- DATABASE_URL=YOUR_DATABASE_URL

# db
  postgres-rec-twitcasting:
    image: postgres:13
    container_name: postgres-rec-twitcasting
    restart: unless-stopped
    environment:
      - POSTGRES_USER=rec-twitcasting-user
      - POSTGRES_PASSWORD=rec-twitcasting-pass
      - POSTGRES_DB=rec_twitcasting
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data

# manage
  manage-frontend-rec-twitcasting:
    image: ghcr.io/miutaku/manage-frontend-rec-twitcasting:latest
    container_name: frontend-rec-twitcasting
    restart: unless-stopped
    ports:
      - 8888:8888

  manage-backend-rec-twitcasting:
    image: ghcr.io/miutaku/manage-backend-rec-twitcasting:latest
    container_name: backend-rec-twitcasting
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
      #- DATABASE_URL=YOUR_DATABASE_URL
