---
name: rec-twitcasting api docker push
on:
  push:
    branches:
      - main
    paths:
      - './api/**'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create image meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.actor }}/rec-twitcasting
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: push container image
        uses: docker/build-push-action@v5
        with:
          file: ./api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
